<?php
//DB TABLES
// TABLES HAVE TO NAMED STARTING WITH "T_" 
// THEN ADD THE NAME YOU WANT "EXAMPLE" 
// AND FINICH BY 3 LETTERS YOU WANT "_EXP" 
// SO YOUR MYSQL TABLE NAME IS T_EXAMPLE_EXP


// DEFINE YOUR TABLE FRIENDLY NAME TO USE IN THE APPLICATION
define('TABLE_EXAMPLE',"T_EXAMPLE_EXP");